### PR TITLE
Organize and Optimize Code

### PR DESCRIPTION
**Pull request by AimenYaseen**
Issue #123 

Organized all routes and tests in different files.

### CODE REVIEW

**Comment by AimenYaseen** [comment]
@GOPAL-YADAV-D 
Please review this and let me know if anything needs to be changed.

**Comment by GOPAL-YADAV-D** [comment]
@AimenYaseen ,This is good to go ,kindly add the new function of calculating factorial, and hcf and lcm   in the restructuring as well

**Comment by AimenYaseen** [comment]
@GOPAL-YADAV-D 
I resolved the conflicts and added hcf_lcm and factorial code. Let me know if anything needs to be fixed.

**Comment by GOPAL-YADAV-D** [comment]
@AimenYaseen ,Thank you for your valuable contibution!!! .The restructuring of code is great.

**Pull request merged**
