### PR TITLE
Feat/hcf and lcm

### PR DESCRIPTION
**Pull request by abhinab-choudhury**
# Ref : #126

- [x] Route math/hcflcm Added
- [x] Test for math/hcflcm added

### CODE REVIEW

**Comment by GOPAL-YADAV-D** [comment]
@abhinab-choudhury kindly resolve the merge conflicts

**Comment by GOPAL-YADAV-D** [comment]
kindly resolve the conflicts, and you are good to go

**Comment by abhinab-choudhury** [comment]
Please merge my PR. I have resolved the conflit

**Comment by GOPAL-YADAV-D** [comment]
@abhinab-choudhury ,Thank you for your valuable contribution .Do check out other repositories from IEEE-VIT

**Pull request merged**
