### PR TITLE
Ashwin95525 patch 2

### PR DESCRIPTION
**Pull request by Ashwin95525**
Added the git commands as code snippets.

### CODE REVIEW

**Comment by GOPAL-YADAV-D** [comment]
@Ashwin95525 , kindly add steps to create a virtual environment and to activate it.

**Comment by Ashwin95525** [comment]
@GOPAL-YADAV-D, Sure I can do that. So should I just contribute under the Contribute.md file and just create a new branch?

**Comment by GOPAL-YADAV-D** [comment]
@Ashwin95525,yes kindly make changes and commit to the same branch from which PR was created there is no need to create a new branch.

**Comment by Ashwin95525** [comment]
@GOPAL-YADAV-D , Thank you for suggesting the idea-steps to create a virtual environment and to activate it. I wrote about it in the "create contributing.md" file and made a new pull request. I hope that will work!!
Thanks

**Comment by varun10sudhir** [comment]
Hi @Ashwin95525 , we will be merging this PR !
Your contributions are appreciated!
Great work

**Comment by Ashwin95525** [comment]
@varun10sudhir Thank you so much  for merging the PR and for your  time I really appreciate it.

**Pull request merged**
