### PR TITLE
Create Contribute.md

### PR DESCRIPTION
**Pull request by Ashwin95525**
Added steps to create a virtual environment and to activate it.

### CODE REVIEW

**Comment by varun10sudhir** [comment]
Hi @Ashwin95525 ,
Kindly add the steps to activate the env in the given CONTRIBUTING.md, no need to make a new file
Thanks

**Comment by Ashwin95525** [comment]
@varun10sudhir Sure I will do that. So I should just edit the contribute.md file and directly commit it right? without making a new branch and creating a new pull request?

**Comment by varun10sudhir** [comment]
Hi @Ashwin95525 ,
Yes no need to make a new branch or PR 
You can continue working on this branch and make your changes
Thanks

**Comment by Ashwin95525** [comment]
@varun10sudhir Thank you for the clarification. As said I made the changes in the contribute.md file- Steps to create a virtual environment and to activate it

**Pull request closed without merging**
