### PR TITLE
Funtionality for addition operation issue 1

### PR DESCRIPTION
**Pull request by badoolee**
I added the addition functionality and tests to the routes and test_app file.

### CODE REVIEW

**Review by badoolee — COMMENTED** [review]
i realized that the person you assign the addition function two weeks ago is yet to do the task so i decided to take it up and do the task. i hope to hear from you soon after reviewing the codes.

**Comment by GOPAL-YADAV-D** [comment]
@badoolee ,kindly resolve the merge conflicts

**Comment by badoolee** [comment]
The merge conflict is resolved.

**Comment by badoolee** [comment]
it's done. The merge conflict issue is fixed.

**Comment by GOPAL-YADAV-D** [comment]
@badoolee ,Thank you for your valuable Contribution!!! .Do check out other repositories from IEEE-VIT .

**Pull request merged**
